/*
 * Joshua Wong - 2/3/18
 * show tables;
 */

CREATE TABLE IF NOT EXISTS MEDIA (
  MEDIA_ID INT(10) NOT NULL AUTO_INCREMENT,
ID VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(300),
CATEGORY VARCHAR(100),
TYPE VARCHAR(10),
  DATE_CREATED DATETIME NOT NULL,
PRIMARY KEY(media_id),
UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS VOTE (
  VOTE_ID INT(10) NOT NULL AUTO_INCREMENT,
  MEDIA_ID INT(10) NOT NULL,
  VOTE_RATING INT(1) NOT NULL,
  DATE_CREATED DATETIME NOT NULL,
PRIMARY KEY(VOTE_ID),
FOREIGN KEY fk_media_id(MEDIA_ID)
REFERENCES MEDIA(MEDIA_ID)
);

CREATE INDEX idx_vote ON VOTE (MEDIA_ID, VOTE_RATING);